name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

    lint:
      runs-on: ubuntu-latest

      steps:
      - name: check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: setup ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: init
        run: npm ci 
      
      - name: Style Check
        run: npm run style-check
      
      - name: Lint Check
        run: npm run lint-check
