name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: setup ssh-agent
          uses: webfactory/ssh-agent@v0.5.3
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Install dependencies
          run: npm ci
        - name: test
          run: npm run test





