name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci && npm run load-contracts
        - name: test
          run: npm run test





